//Projects Main Card Data
import {AiFillGithub} from "react-icons/ai";
import { MdOutlineVideoLabel } from "react-icons/md";


const webData = [
    {
        id:1,
        title: "Weather App",
        // description: "Project to gain experience using Fetch API. Uses Open Weather API for live updates",
        // image: "https://drive.google.com/uc?export=view&id=INSERT_HERE_YOUR_GOOGLE_DRIVE_IMAGE_ID",
        //drive.google.com/file/d//view?usp=share_link
        image: "https://drive.google.com/uc?export=view&id=1JRs2OgFXcVj_r9ksJtnpksdO_4ShwzY1",
        github: "https://github.com/hakeem0114/Weather-App",
        demo:"https://hakeem0114.github.io/Weather-App/",
        inProgress:"0",
        html: <AiFillGithub/>,
        js: <AiFillGithub/>,
        css:  <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",

    },
    {
        id:2,
        title: "Library App",
        // description: "Project to gain experience using Fetch API. Uses Open Weather API for live updates",
        image: "https://drive.google.com/uc?export=view&id=1wtD6UT5ybmcXs7RhIKz902xY-bacKjzF",
        github: "https://github.com/hakeem0114/Library-App",
        demo: "https://hakeem0114.github.io/Library-App/",
        inProgress:"0",
        html: <AiFillGithub/>,
        js: <AiFillGithub/>,
        css:  <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:3,
        title: "My Portfolio",
        image: "https://drive.google.com/uc?export=view&id=11sdKk5-4kf980gSgu5gj0HmMMW71Pw7Z",
        github: "https://github.com/hakeem0114/Portfolio",
        demo: "#",
        inProgress:"0",
        react:  <AiFillGithub/>,
        html: <AiFillGithub/>,
        js: <AiFillGithub/>,
        css:  <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",

    },
    {
        id:4,
        title: "Travel Journal",
        image: "https://drive.google.com/uc?export=view&id=1rTqMbITJmuei6F1oweQs-DjRLUsYPO3k",
        github: "https://github.com/hakeem0114/Travel-Journal",
        demo: "https://hakeem0114.github.io/Travel-Journal/",
        inProgress:"0",
        react:  <AiFillGithub/>,
        html: <AiFillGithub/>,
        js: <AiFillGithub/>,
        css:  <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:5,
        title: "Sign-Up Page",
        image: "https://drive.google.com/uc?export=view&id=10RJR9BIQk-q_ITshI_XWs_z8Tzv2k49V",
        github: "https://github.com/hakeem0114/Sign-up-Page",
        demo: "https://hakeem0114.github.io/Sign-up-Page/",
        inProgress:"0",
        html: <AiFillGithub/>,
        js: <AiFillGithub/>,
        css:  <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:7,
        title: "Admin Dashboard",
        image: "https://drive.google.com/uc?export=view&id=1XiGM15TxgabETnDTKnaGhxc3iJ_Yq29Y",
        github: "https://github.com/hakeem0114/Dashboard",
        demo: "https://hakeem0114.github.io/Dashboard/",
        inProgress:"0",
        html: <AiFillGithub/>,
        js: <AiFillGithub/>,
        css:  <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:7,
        title: "Calculator",
        image: "https://drive.google.com/uc?export=view&id=1wZTgLAooixEcxdGvMs65Y18DlQ5mZiGm",
        github: "https://github.com/hakeem0114/Calculator",
        demo: "https://hakeem0114.github.io/Calculator/",
        inProgress:"0",
        html: <AiFillGithub/>,
        js: <AiFillGithub/>,
        css:  <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:8,
        title: "Etch-A-Sketch",
        image: "https://drive.google.com/uc?export=view&id=1Craz0vwStPgkc6mlLK460ETKxYsssMFN",
        github: "https://github.com/hakeem0114/Etch-a-Sketch",
        demo: "https://hakeem0114.github.io/Etch-a-Sketch/",
        inProgress:"0",
        html: <AiFillGithub/>,
        js: <AiFillGithub/>,
        css:  <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },

]


const mechData = [
    {
        id:1,
        title: "Security System",
        // description: "Project to gain experience using Fetch API. Uses Open Weather API for live updates",
        // image: "https://drive.google.com/uc?export=view&id=INSERT_HERE_YOUR_GOOGLE_DRIVE_IMAGE_ID",
        image: "https://img.freepik.com/free-photo/female-inventor-creating-her-workshop_23-2149067245.jpg?w=900&t=st=1677563652~exp=1677564252~hmac=927d21599aef0b26ccd01c0c9470ebe5e0b8e13664e7cdef3f5750dc65380c5b",
        // github: "#",
        demo:"https://drive.google.com/file/d/1pmw5eFL7UWJ9BhHqsgVNzWCnWBGa0MP4/view?usp=share_link",
        inProgress:"0",
        arduino: <AiFillGithub/>,
        type: "mech",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",

    },
    {
        id:2,
        title: "Autonomous Car",
        // description: "Project to gain experience using Fetch API. Uses Open Weather API for live updates",
        image: "https://drive.google.com/uc?export=view&id=1H2Qgej0S3MvOCEc8EzQn9O8nYAUORwIZ",
        github: "https://github.com/hakeem0114/Autonomous_Robot",
        demo: "https://drive.google.com/file/d/1vuiqtAMu6i7tJWlLJrQq0xOJ7AMvlkVg/view?usp=share_link",
        inProgress:"0",
        arduino: <AiFillGithub/>,
        matlab: <AiFillGithub/>,
        type: "mech",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:3,
        title: "Silica Removal System",
        image: "https://drive.google.com/uc?export=view&id=1WdKDUOAf_V4cqUM6b_ZJTGi0CmDoNo16",
        github: "https://github.com/hakeem0114/Silica_Removal_System",
        demo: "https://drive.google.com/file/d/1U5kPrNT-2evOZWIiyqMlXTrlk27xrf82/view?usp=share_link",
        inProgress:"0",
        arduino:  <AiFillGithub/>,
        matlab: <AiFillGithub/>,
        cad: <AiFillGithub/>,
        type: "mech",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",

    },
    {
        id:4,
        title: "4-Bit Adder-Subtractor Unit",
        image: "https://drive.google.com/uc?export=view&id=1UI6Q5dDxuZ4drKNR0K-DTTXlo6wxxmhy",
        // github: "https://github.com/hakeem0114/Travel-Journal",
        // demo: "https://hakeem0114.github.io/Travel-Journal/",
        inProgress:"0",
        vhdl:  <AiFillGithub/>,
        type: "mech",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:5,
        title: "Concrete mixer",
        image: "https://drive.google.com/uc?export=view&id=1C3IYWO4kMtHMgChTsj9EqAN777XjFtVd",
        // github: "https://github.com/hakeem0114/Sign-up-Page",
        demo: "https://docs.google.com/document/d/1ECelAbCbWXZJRvZgPsbFtHVwWZFgd4HTF1RfkhN6xNU/edit?usp=share_link",
        inProgress:"0",
        matlab: <AiFillGithub/>,
        cad: <AiFillGithub/>,
        type: "mech",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:7,
        title: "Calibrated Load Sensor",
        image: "https://drive.google.com/uc?export=view&id=16blSTtsC6QTwhm-fLIivpYMGr_WwDutS",
        github: "https://github.com/hakeem0114/Calibrated_Load_Sensor",
        demo: "https://drive.google.com/file/d/19BvUV9-WocpSEG_llmYmK19gOkKIxJWZ/view?usp=share_link",
        inProgress:"0",
        matlab: <AiFillGithub/>,
        arduino: <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },
    {
        id:7,
        title: "Solar Tracking System",
        image: "https://drive.google.com/uc?export=view&id=1MEJ6_cft2XgI2Yozq-9EmddtnqhoLlSW",
        github: "https://github.com/hakeem0114/Solar_Tracking_System/",
        demo: "https://drive.google.com/uc?export=view&id=1eZim7bFTLD3cdHdKW1mlDTMlITo3wctQ",
        inProgress:"0",
        matlab: <AiFillGithub/>,
        arduino: <AiFillGithub/>,
        type: "web",
        gitIcon: "https://img.icons8.com/ios-filled/256/github.png",
        demoIcon: "https://img.icons8.com/ios-filled/256/system-task.png",
    },

]


export{

    webData,
    mechData,
}